### ISSUE TITLE
`unobserve is not a function` when using removeObserver()

### ISSUE THREAD

**Issue by ajilderda** [scaccogatto/vue-waypoint#18]
Hi scaccogatto, I want to fire a function only once when an element is in the viewport. Therefore I'm trying to use `VueWaypoint.removeObserver (Element el, function callback)`.

I assumed this would work:
```
isInViewport: function(event) {
  // this is where I do stuff
  VueWaypoint.removeObserver(event.el);
}
```
`isInViewport` is succesfully triggered by Waypoint, but I'm getting a `TypeError: t.unobserve is not a function`. I guess I oversee something. Can you help me out?

**Comment by scaccogatto** [comment]
Since this plugin is based on `Intersection Observer API` you should first read this:
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

VueWaypoint.removeObserver accepts the `observer` as its first parameter and `element` as it second one.

You may point out then that the README is wrong. You may edit it (by pushing a pull request) and fix it following this line:

https://github.com/scaccogatto/vue-waypoint/blob/master/src/intersectionObserver.js#L20

**Comment by ajilderda** [comment]
Thanks for your reply! I managed to solve it for my use case with the reference to Intersection Observer you provided. I’d love to add a PR, but I’m not comfortable in doing so since both the Intersection Observer API and Vue are quite new to me. You may close this issue if you like.
