### ISSUE TITLE
Attach data to callback ??

### ISSUE THREAD

**Issue by OG3NS3C** [scaccogatto/vue-waypoint#34]
Just installed and uninstalled because can't attach a data to the callback event...
I am wondering why you call this a "Vue plugins" if we can't attach  data or components to the callback.

```
    <template v-for="(event,index) in getEventsList">
       <div class="ctn-message" 
            v-waypoint="{ active: true, callback: onScreen(event) }"
            >{{event.content}}</div>
</template>
```
OR 

    <template v-for="(event,index) in getEventsList">
       <div class="ctn-message" 
            v-waypoint="{ active: true, callback: onScreen, data:event}"
            >{{event.content}}</div>
</template>

We need this...thanks.

**Comment by scaccogatto** [comment]
Before answering your question I want to point out that you are being rude towards a guy that is maintaining an open source vue plugin since 2018, for free.

Besides that, I am really sorry that your poor understanding of the DOM is limiting you building your application. Since you can do what you asked without changing the nature of `vue-waypoint` I am setting this issue to: `enhancement`. We can discuss this in a RFC ticket.

Anyway, since my main purpose here is being helpful towards the vue community that gave me alot, I edited the demo (you can find it here: https://scaccogatto.github.io/vue-waypoint/, source here: https://github.com/scaccogatto/vue-waypoint/blob/c8c9058230fa8bca0269e4009ba488753d69f065/docs/index.html#L99) in order to include a specific example for you that show the feasibility of the specific request.

**Comment by OG3NS3C** [comment]
What are you saying ? I edited your plugins callback function to attach datas...
And now I can see the update() of your plugin doesn't work properly.

You plugin is 40 lines of codes, my project is 64000.

**Comment by scaccogatto** [comment]
![image](https://user-images.githubusercontent.com/3670888/75752937-fee9d100-5d29-11ea-867c-ed5b3cb19ac5.png)

Did you read that? It says "trigger functions based on elements' positions, based on viewport".
I never mentioned event dispatching, or reactivity.

You are just being rude and clueless about the project's scope. I am closing this and reporting you.
