### ISSUE TITLE
Return parent element as current target?

### ISSUE THREAD

**Issue by dblodorn** [scaccogatto/vue-waypoint#5]
Hi @scaccogatto

I'm using v-waypoints in a rendered list, and am having issues trying to access the parent element that holds each v-waypoint component with the attached handler, are there any simple ways to achieve this? - 

    this.$el //returns everything.

here's the template markup(pug):

    section.hero-slide(v-for="(slide, index) in slides" :id="'hero-slide-' + (index + 1)")
      v-waypoint#wp-1(@waypoint-in="heroIn(index)")
      v-waypoint#wp-2(@waypoint-out="heroOut(index)")
      article.hero-articles(@click="clickReport" :id="'hero-article-' + (index + 1)")
        h2.waypoint-text {{slide.title}}

and the handler:

     methods: {
        heroIn (index, e) {
          console.log('hero ' + index + ' in')
          console.log(e.currentTarget)
          console.log(this.$el)
        },
        heroOut (index) {
          console.log('hero ' + index + ' out')
        }
      }

Is there support for this currently?

**Comment by scaccogatto** [comment]
so, what you are trying to do is having `document.querySelector('#wp-1')` DOM element inside `heroIn`, am I right?

**Comment by scaccogatto** [comment]
Since I didn't receive any reply to my question in 7 days I assume the problem does not exist anymore (or it is solved).
I am marking this as solved and putting a reference to the [Vue API guide](https://vuejs.org/v2/api/#ref)
(with `ref="theRefName"` you can have any DOM or Component reference you need easily) in order to help any other visitor.

**Comment by dblodorn** [comment]
Thank you @scaccogatto I appreciate your reply.
