### ISSUE TITLE
did bundle size increase going to version 4?

### ISSUE THREAD

**Issue by jaunt** [scaccogatto/vue-waypoint#69]
Hello, 

Looking at bundle phobia, the gzipped bundle size went from 1.1kB to 40.4kB betrween version 3 and 4.  Does that seem right?

https://bundlephobia.com/package/vue-waypoint

**Comment by scaccogatto** [comment]
This repository contains a whole application in order to have a working test.
This does not mean that you should use the whole repository (you can use just the component, which is (https://github.com/scaccogatto/vue-waypoint/blob/master/src/components/Waypoint/component.vue)

But if you can strip everything off, PRs are welcome!

**Comment by scaccogatto** [comment]
Can you make a PR with a vite-based build system?

**Comment by iamandrewluca** [comment]
Sure. Later today will be done!

**Comment by iamandrewluca** [comment]
@scaccogatto ok so the build is fine, but it seems there is a problem with the actual code using the latest `vue`, the `@change` callback is called indefinitely 🤔

**Comment by scaccogatto** [comment]
This hook is sensitive, I would like to investigate.
If you open the PR with just the build change I can maybe try to fix the thing.

**Comment by iamandrewluca** [comment]
@scaccogatto PR ready for review!
